
name: reactions


on: pull_request

jobs:
  example_comment_pr:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest,windows-latest,macOS-latest]
     
    name: sankho kyun
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
             thank you for contributing in my repository! :wave:
          reactions: eyes, rocket
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
