
name: reactions


on: pull_request

jobs:
  example_comment_pr:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest,windows-latest,macOS-latest]
     
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          message: |
             Hello world ! :wave:
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
